name: Run training (manual)

on:
  workflow_dispatch:

jobs:
  run-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run training script
        env:
          SERVICEACCOUNT: ${{ secrets.SERVICEACCOUNT}}
        run: |
          export NEW_HF_HOME="${RUNNER_TEMP}/hf_cache"
          mkdir -p "$NEW_HF_HOME"
          echo "Using HF_HOME=$NEW_HF_HOME"
          export TRANSFORMERS_CACHE="${NEW_HF_HOME}/transformers"
          export HF_HOME="$NEW_HF_HOME"
          python -m pip install accelerate
          sudo apt-get update && sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision || true
          python -m pip install -r requirements.txt
          python model/training_pipeline.py --gen-enabled
