name: Run training (manual)

on:
  workflow_dispatch:

jobs:
  run-training:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Run training script
        env:
          SERVICEACCOUNT: ${{ secrets.SERVICEACCOUNT}}
        run: |
          sudo apt-get update && sudo apt-get install -y shellcheck
          python -m pip install --upgrade pip
          python -m pip install --index-url https://download.pytorch.org/whl/cpu torch torchvision || true
          python -m pip install -r requirements.txt
          python -m pip install accelerate  
          python model/training_pipeline.py --gen-enabled
